version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - rm -rf terraform
      - wget -O terraform.zip https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  
  pre_build:
    commands:
      - cd terraform
      - terraform init
  
  build:
    commands:
      - cd terraform
      - terraform apply -auto-approve
  
  post_build:
    commands:
      - echo "Terraform apply completed successfully"
      - terraform output
