version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - terraform --version
  
  pre_build:
    commands:
      - cd terraform
      - terraform init
  
  build:
    commands:
      - terraform apply -auto-approve
  
  post_build:
    commands:
      - echo "Terraform apply completed successfully"
      - terraform output